//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PieChart
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CAR
    {
        public int CAR_ID { get; set; }
        [DisplayName("Manufacturer")]
        public string MANUFACTURER { get; set; }
        [DisplayName("Model")]
        public string MODEL { get; set; }
        [DisplayName("Year")]
        public string YEAR { get; set; }
        [DisplayName("Producing Country")]
        public string PRODUCING_COUNTRY { get; set; }
    }
}
